//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkMapData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetworkDataEntities : DbContext
    {
        public NetworkDataEntities()
            : base("name=NetworkDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Closet> Closets { get; set; }
        public virtual DbSet<Network> Networks { get; set; }
        public virtual DbSet<PatchPanel> PatchPanels { get; set; }
        public virtual DbSet<Port> Ports { get; set; }
        public virtual DbSet<PortGroup> PortGroups { get; set; }
        public virtual DbSet<PortType> PortTypes { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Switch> Switches { get; set; }
        public virtual DbSet<VlanTag> VlanTags { get; set; }
    }
}
