//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkMapData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatchCable
    {
        public int Id { get; set; }
        public Nullable<int> PortAId { get; set; }
        public Nullable<int> PortBId { get; set; }
    
        public virtual Port PortA { get; set; }
        public virtual Port PortB { get; set; }
    }
}
