//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkMapData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Switch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Switch()
        {
            this.Networks = new HashSet<Network>();
            this.PortGroups = new HashSet<PortGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ModelInfo { get; set; }
        public int ClosetId { get; set; }
    
        public virtual Closet Closet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Network> Networks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PortGroup> PortGroups { get; set; }
    }
}
